name: w3-deploy ğŸŒ

on:
  push:
    branches:
      - main

jobs:
  publish-with-web3-storage:
    runs-on: ubuntu-latest

    env:
      WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}

    steps:
      - name: ğŸ“‚ checkout
        uses: actions/checkout@v3

      - name: ğŸ“¦ setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: ğŸ”§ pnpm build
        uses: ./.github/actions/pnpm-build
        with:
          enable-corepack: true

      - name: ğŸ”¥ upload to web3
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: "out"

      - run: echo `cid:${{ steps.web3.outputs.cid }}`

      - run: echo `url:${{ steps.web3.outputs.url }}`
